---
- name: nginx - install and start service
  hosts: all
  become: true
  
  tasks:
  - name: install nginx using apt module
    apt:
      name: nginx
      state: latest
  - name: start nginx
    service:
      name: nginx
      state: stopped      
