---
- name: nginx - install and start service
  hosts: all
  become: true
  sudo_pass: anusree
  
  tasks:
  - name: install nginx using apt module
    apt:
      name: nginx
      state: latest
  - name: start nginx
    service:
      name: nginx
      state: started      